services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"  # Assuming frontend runs on port 80 inside the container
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"  # Assuming backend runs on port 8080
    environment:
      - FLASK_ENV=production
      - AMADEUS_CLIENT_ID=${AMADEUS_CLIENT_ID}
      - AMADEUS_CLIENT_SECRET=${AMADEUS_CLIENT_SECRET}
      - GCP_SERVICE_ACCOUNT=${GCP_SERVICE_ACCOUNT}
      - GCS_BUCKET_NAME=${GCS_BUCKET_NAME}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
